language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache/files

install: composer update --prefer-dist

script: ./phpunit --coverage-text